# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: 1

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: VaultReadKV@4
      inputs:
        strUrl: 'http://192.168.29.56:8200/ui/vault/secrets'
        ignoreCertificateChecks: true
        useProxy: 'none'
        strAuthType: 'clientToken'
        strToken: 's.Z2iS4rfdTa5494VLNXHgDXc5'
        strKVEnginePath: 'secret'
        kvVersion: 'v2'
        strPrefixType: 'none'
        replaceCR: false
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
